### ISSUE TITLE
usb_cam is empty

### ISSUE THREAD

**Issue by mridul2899** [SpandanKumarSahu/Swarm_AprilTags#1]
catkin_make won't build usb_cam as it is empty. Hence, roslaunch usb_cam usb_cam-test.launch also won't work.

**Comment by SpandanKumarSahu** [comment]
[Here](https://github.com/ros-drivers/usb_cam) is the link for the `usb_cam`. Download/clone the contents into the `usb_cam` folder under `src/`.
